# Generated by Django 4.1.2 on 2022-11-22 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('biografico', 'Biográfico'), ('humor', 'Humor'), ('acao', 'Ação'), ('outros', 'Outros')], max_length=100)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
            ],
        ),
    ]
